""" This module finds the electrostatics from a 3D potential map in Gaussian
    (Software) cube format at the points on the surface of protein. The points
    on the surface of the protein are obtained by MSMS program from MGL Tools

    Author: Dibyajyoti Maity

Usage:  md_davis electrostatics [options] PDB_FILE OUTPUT_DIRECTORY

Options:
  -m, --msms PATH                   full path to MSMS executable [default: ~/]
  -d, --delphi PATH                 full path to Delphi executable [default: ~/]
  -r, --radius PATH                 path to radius file
  -c, --charge PATH                 path to charge file
  -g, --grid_size <odd_int>         Grid size to use for Delphi calculation
  -v, --vertices <filename.vert>    vertices file generated by MSMS
  -s, --surface <surface.pdb>       file containing surface vertices created by
                                    running 'md_davis vert2pdb' on vertex file
                                    created by MSMS
  --surface_potential               Whether to calculate the electrostatic
                                    potential on the surface or not
  --center                          Center the grid for Delphi at the origin
"""

import os
import docopt
import subprocess


def dir_path(path):
    if os.path.isdir(path):
        return path
    else:
        raise NotADirectoryError(path)


# TODO: Remove hard coded application paths and names
def run_msms(pdb_file, output_directory=None, msms_path='~/', executable="msms.x86_64Linux2.2.6.1"):
    """ Calculate triangulated surface using MSMS program """
    basename, _ = os.path.splitext(os.path.basename(pdb_file))

    if not output_directory:
        output_directory = './'
    elif output_directory[-1] != '/':
        output_directory = output_directory + '/'
    else:
        pass

    if not os.path.isdir(output_directory):
        os.mkdir(output_directory)

    with open(output_directory + basename + '.xyz', 'w') as xyz_file:
        subprocess.run([msms_path + "pdb_to_xyzrn", pdb_file], stdout=xyz_file)

    subprocess.run([msms_path + executable,
                     "-if", basename + ".xyz",
                     "-of", basename,
                     "-probe_radius", "1.4"], cwd=output_directory)
    return output_directory + basename + '.vert'


def run_delphi(pdb_file, output_directory, output_filename,
    delphi_path, radius_file, charge_file, grid_size=101, surface=None, center=False):
    """ Run Delphi on protein surface created by MSMS program """
    # TODO: Rewrite using template string
    if not os.path.isdir(output_directory):
        os.mkdir(output_directory)

    parameters = [
        f'in(pdb,file="{pdb_file}")',
        f'in(siz,file="{radius_file}")',
        f'in(crg,file="{charge_file}")',
        f'gsize={grid_size}',
        f'salt=0.10',
        f'exdi=80',
        f'linit=2000',
        f'maxc=0.0000000001',
        f'out(phi, file="{output_directory}/{output_filename}.cub", format="cube")',
    ]
    if center:
        parameters += ['acenter(0,0,0)']
    if surface:
        parameters += [
            f'in(frc,file="{surface}")',
            f'out(frc, file="{output_directory}/{output_filename}.pot")',
            f'site(Atom, Potential, Reaction, Coulomb, Field)',
        ]
    print('\n'.join(parameters) + '\n', file=open(f'{output_filename}_tmp.prm', 'w'))
    subprocess.run([delphi_path, f'{output_filename}_tmp.prm'])
    subprocess.run(['rm', f'{output_filename}_tmp.prm'])


def main(argv=None):
    """ Get the electrosatic potential on the surface points generated by MSMS """
    if argv:
        args = docopt.docopt(__doc__, argv=argv)
    else:
        args = docopt.docopt(__doc__)

    this_script_path = os.path.dirname(os.path.realpath(__file__))

    pdb_file = args['PDB_FILE']
    output_filename = os.path.splitext(os.path.basename(pdb_file))[0]

    surface_file = None
    if args['--surface_potential']:
        if args['--surface']:
            surface_file = args['--surface']
        else:
            if args['--vertices']:
                vert_file = args['--vertices']
            else:
                vert_file = run_msms(pdb_file=pdb_file,
                                    output_directory=args['OUTPUT_DIRECTORY'],
                                    msms_path=args['--msms'])
            surface_file = f"{args['OUTPUT_DIRECTORY']}/{output_filename}_surf.pdb"
            # TODO: remove this subprocess run with a function
            subprocess.run(['python', f'{this_script_path}/vert2pdb.py', vert_file, pdb_file, '-o', surface_file])

    run_delphi(pdb_file=pdb_file,
               output_directory=args['OUTPUT_DIRECTORY'],
               output_filename=output_filename,
               surface=surface_file,
               delphi_path=args['--delphi'],
               radius_file=args['--radius'],
               charge_file=args['--charge'],
               grid_size=args['--grid_size'],
               center=args['--center'],
    )


if __name__ == '__main__':
    main()
