THREE_TO_ONE = {
    'ALA': 'A',
    'ARG': 'R',
    'ASN': 'N',
    'ASP': 'D',
    'CYS': 'C',
    'GLN': 'Q',
    'GLU': 'E',
    'GLY': 'G',
    'HIS': 'H',
    'ILE': 'I',
    'LEU': 'L',
    'LYS': 'K',
    'MET': 'M',
    'PHE': 'F',
    'PRO': 'P',
    'SER': 'S',
    'THR': 'T',
    'TRP': 'W',
    'TYR': 'Y',
    'VAL': 'V',
}

ONE_TO_THREE = {
    'A': 'ALA',
    'R': 'ARG',
    'N': 'ASN',
    'D': 'ASP',
    'C': 'CYS',
    'Q': 'GLN',
    'E': 'GLU',
    'G': 'GLY',
    'H': 'HIS',
    'I': 'ILE',
    'L': 'LEU',
    'K': 'LYS',
    'M': 'MET',
    'F': 'PHE',
    'P': 'PRO',
    'S': 'SER',
    'T': 'THR',
    'W': 'TRP',
    'Y': 'TYR',
    'V': 'VAL',
}

NAME_TO_THREE = {
    'Alanine': 'ALA',
    'Arginine': 'ARG',
    'Asparagine': 'ASN',
    'Aspartic acid': 'ASP',
    'Cysteine': 'CYS',
    'Glutamine': 'GLN',
    'Glutamic acid': 'GLU',
    'Glycine': 'GLY',
    'Histidine': 'HIS',
    'Isoleucine': 'ILE',
    'Leucine': 'LEU',
    'Lysine': 'LYS',
    'Methionine': 'MET',
    'Phenylalanine': 'PHE',
    'Proline': 'PRO',
    'Serine': 'SER',
    'Threonine': 'THR',
    'Tryptophan': 'TRP',
    'Tyrosine': 'TYR',
    'Valine': 'VAL',
}

NAME_TO_ONE = {
    'Alanine'       : 'A',
    'Arginine'      : 'R',
    'Asparagine'    : 'N',
    'Aspartic acid' : 'D',
    'Cysteine'      : 'C',
    'Glutamine'     : 'Q',
    'Glutamic acid' : 'E',
    'Glycine'       : 'G',
    'Histidine'     : 'H',
    'Isoleucine'    : 'I',
    'Leucine'       : 'L',
    'Lysine'        : 'K',
    'Methionine'    : 'M',
    'Phenylalanine' : 'F',
    'Proline'       : 'P',
    'Serine'        : 'S',
    'Threonine'     : 'T',
    'Tryptophan'    : 'W',
    'Tyrosine'      : 'Y',
    'Valine'        : 'V',
}

THREE_TO_NAME = {
    'ALA': 'Alanine',
    'ARG': 'Arginine',
    'ASN': 'Asparagine',
    'ASP': 'Aspartic acid',
    'CYS': 'Cysteine',
    'GLN': 'Glutamine',
    'GLU': 'Glutamic acid',
    'GLY': 'Glycine',
    'HIS': 'Histidine',
    'ILE': 'Isoleucine',
    'LEU': 'Leucine',
    'LYS': 'Lysine',
    'MET': 'Methionine',
    'PHE': 'Phenylalanine',
    'PRO': 'Proline',
    'SER': 'Serine',
    'THR': 'Threonine',
    'TRP': 'Tryptophan',
    'TYR': 'Tyrosine',
    'VAL': 'Valine',
}

ONE_TO_NAME = {
    'A': 'Alanine',
    'R': 'Arginine',
    'N': 'Asparagine',
    'D': 'Aspartic acid',
    'C': 'Cysteine',
    'Q': 'Glutamine',
    'E': 'Glutamic acid',
    'G': 'Glycine',
    'H': 'Histidine',
    'I': 'Isoleucine',
    'L': 'Leucine',
    'K': 'Lysine',
    'M': 'Methionine',
    'F': 'Phenylalanine',
    'P': 'Proline',
    'S': 'Serine',
    'T': 'Threonine',
    'W': 'Tryptophan',
    'Y': 'Tyrosine',
    'V': 'Valine',
}
